In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from useful_func import *
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [3]:
df = pd.read_csv("customer_segmentation_uncleaned_data.csv")
df.head()

,CustomerID,Age,Annual_Income_k$,Spending_Score,Purchase_Frequency,Gender
0,1,56.0,65.03,23,3,Female
1,2,69.0,103.57,40,3,Male
2,3,46.0,47.20,82,7,Female
3,4,32.0,44.72,46,8,Female
4,5,60.0,57.67,67,2,Female

In [4]:
# fill missing vaalues

In [5]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Annual_Income_k$"] = df["Annual_Income_k$"].fillna(df["Annual_Income_k$"].mean())

In [6]:
# fill outliers

In [7]:
df["Annual_Income_k$"] = df["Annual_Income_k$"].clip(lower=0, upper=200)

In [8]:
# # Encoding : Gender columns to convert label Encoder

In [9]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [10]:
# Scaling :

In [11]:
scaler = StandardScaler()
cols_to_scale = ["Age", "Annual_Income_k$", "Spending_Score", "Purchase_Frequency"]
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

In [12]:
df

,CustomerID,Age,Annual_Income_k$,Spending_Score,Purchase_Frequency,Gender
0,1,0.856678,0.166310,-0.693726,-0.894227,0
1,2,1.747915,1.661890,-0.296783,-0.894227,1
2,3,0.171110,-0.525600,0.683898,0.892235,0
3,4,-0.788684,-0.621838,-0.156686,1.338850,0
4,5,1.130905,-0.119302,0.333655,-1.340842,0
...,...,...,...,...,...,...
99995,99996,-0.925797,0.100340,-0.857172,-0.894227,1
99996,99997,0.651008,-1.457330,0.730597,-0.447611,1
99997,99998,-0.720127,-0.301690,0.707247,1.338850,1
99998,99999,0.925234,0.583085,-0.670376,0.892235,0
99999,100000,-1.611365,1.414696,-0.413531,-0.000996,1

In [13]:
# #import csv
df.to_csv("Cleaned_Data.csv", index=False)

In [ ]:
`